# : Manager [[[

[manager]
cwd = { fg = "#211a14" }

# Tab
tab_active = { fg = "#ffffff", bg = "#845415", bold = true }
tab_inactive = { fg = "#ffddbb", bg = "#2b1700" }
tab_width = 1

# Find
find_keyword = { fg = "#ba1a1a", bold = true, italic = true, underline = true }
find_position = { fg = "#ba1a1a", bold = true, italic = true }

# Marker
marker_copied = { fg = "#b0d168", bg = "#b0d168" }
marker_cut = { fg = "#d9e9b6", bg = "#d9e9b6" }
marker_marked = { fg = "#ba1a1a", bg = "#ba1a1a" }
marker_selected = { fg = "#56633c", bg = "#56633c" }

# Count
count_copied = { fg = "#141f01", bg = "#d9e9b6" }
count_cut = { fg = "#141f01", bg = "#d9e9b6" }
count_selected = { fg = "#ffffff", bg = "#56633c" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#845415" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#ffffff", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#845415", fg = "#ffffff", bold = true }
normal_alt  = { bg = "#f1dfd0", fg = "#50453a" }

# Select mode
select_main = { bg = "#725a41", fg = "#ffffff", bold = true }
select_alt  = { bg = "#f1dfd0", fg = "#50453a" }

# Unset mode
unset_main = { bg = "#56633c", fg = "#ffffff", bold = true }
unset_alt  = { bg = "#f1dfd0", fg = "#50453a" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#845415", bg = "#fff8f4" }
progress_error = { fg = "#ba1a1a", bg = "#fff8f4" }

# Permissions
permissions_t = { fg = "#bea68e" }
permissions_w = { fg = "#a4b484" }
permissions_x = { fg = "#ed8080" }
permissions_r = { fg = "#9cc640" }
permissions_s = { fg = "#ff9122" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#845415" }
active = { fg = "#56633c", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#845415" }
value = { fg = "#211a14" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#845415", bg = "#ffffff" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#845415" }
title = {}
hovered = { fg = "#d9e9b6", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#fff8f4" }
cand = { fg = "#845415" }
rest = { fg = "#ffffff" }
desc = { fg = "#211a14" }
separator = " ‚ñ∂ "
separator_style = { fg = "#211a14" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#211a14" }
run = { fg = "#211a14" }
footer = { fg = "#ffffff", bg = "#725a41" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#56633c" }
title_warn = { fg = "#845415" }
title_error = { fg = "#ba1a1a" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#ffdad6" },
    { name = "*", is = "exec", fg = "#410002" },

    # Fallback
    { name = "*", fg = "#211a14" },
    { name = "*/", fg = "#845415" },
]

# : ]]]